### Listar todos eventos
GET localhost:2004/api/events

### Pegar evento pelo ID
GET localhost:2004/api/events/1/

### Inserir novo evento
POST localhost:2004/api/events/
Content-Type: application/json

{
    "title": "Título",
    "date": "17/02/2004",
    "time_start": "17:55",
    "time_end": "19:22",
    "address": "Rua Dr Antonio Pereira, 136 - Vassouras, RJ",
    "location": "-11.11111111111123 22.33333333333",
    "description": "Descrição do evento",
    "image": "?"
}

### Apagar um evento pelo ID
DELETE localhost:2004/api/events/1/
