services:

  ## PostgreSQL
  postgresql:
    container_name: postgres
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sirqueira-postgres
    ports:
      - "12345:5432"  # Aqui foi feita a mudança: porta externa 12345 mapeada para a porta interna 5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
